INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (31, null, 'СУМКИ_ХОККЕЙНЫЕ', 'Сумка хоккейная', 'СУМКИ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (32, null, 'СУМКИ_ДЛЯ_ПРИНАДЛЕЖНОСТЕЙ', 'Сумка для принадлежностей', 'СУМКИ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (33, 'ЧЕХЛЫ', 'АКСЕССУАРЫ_ДЛЯ_КОНЬКОВ', 'Чехлы', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (34, 'ЛЕЗВИЯ', 'АКСЕССУАРЫ_ДЛЯ_КОНЬКОВ', 'Лезвия', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (35, 'СТАКАНЫ', 'АКСЕССУАРЫ_ДЛЯ_КОНЬКОВ', 'Стаканы', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (42, 'ПОЯСА_И_ПОДТЯЖКИ', 'АКСЕССУАРЫ_ДЛЯ_ИГРОКА', 'Пояс/Подтяжки', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (43, 'ШАЙБЫ', 'ШАЙБЫ_И_МЯЧИ', 'Шайба', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (44, 'МЯЧИ', 'ШАЙБЫ_И_МЯЧИ', 'Мяч', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (45, null, 'ВОРОТА', 'Ворота', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (46, null, 'ДОСКИ_ТАКТИЧЕСКИЕ', 'Доска тактическая', 'РАЗНОЕ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (1, null, 'КОНЬКИ_ХОККЕЙНЫЕ', 'Коньки', 'КОНЬКИ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (2, null, 'КОНЬКИ_РОЛИКОВЫЕ', 'Коньки роликовые', 'КОНЬКИ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (3, null, 'НАГРУДНИК_ИГРОКА', 'Нагрудник', 'ЗАЩИТА_ИГРОКА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (4, null, 'ЩИТКИ_ИГРОКА', 'Щитки', 'ЗАЩИТА_ИГРОКА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (9, null, 'ВИЗОРЫ_И_МАСКИ_ИГРОКА', 'Визор/Маска', 'ЗАЩИТА_ИГРОКА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (10, null, 'ЗАЩИТА_ШЕИ_ИГРОКА', 'Защита шеи', 'ЗАЩИТА_ИГРОКА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (11, null, 'ПЕРЧАТКИ_ИГРОКА', 'Перчатки', 'ЗАЩИТА_ИГРОКА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (12, null, 'ЗАЩИТА_ЗАПЯСТЬЯ_ИГРОКА', 'Защита запястья', 'ЗАЩИТА_ИГРОКА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (13, null, 'КЛЮШКА_ИГРОКА', 'Клюшка', 'КЛЮШКИ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (14, null, 'КЛЮШКА_ВРАТАРЯ', 'Вратарская клюшка', 'КЛЮШКИ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (15, null, 'ТРУБЫ', 'Труба', 'КЛЮШКИ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (16, null, 'КРЮКИ', 'Крюк', 'КЛЮШКИ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (17, null, 'ГАМАШИ', 'Гамаши', 'ОДЕЖДА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (22, null, 'КОНЬКИ_ВРАТАРЯ', 'Коньки вратаря', 'ВРАТАРСКАЯ_ФОРМА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (23, null, 'ЩИТКИ_ВРАТАРЯ', 'Щитки вратаря', 'ВРАТАРСКАЯ_ФОРМА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (24, null, 'ШЛЕМ_ВРАТАРЯ', 'Шлем вратаря', 'ВРАТАРСКАЯ_ФОРМА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (25, null, 'БЛИН_И_ЛОВУШКА_ВРАТАРЯ', 'Блин/ловушка вратаря', 'ВРАТАРСКАЯ_ФОРМА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (26, 'ЗАЩИТА_ШЕИ_ВРАТАРЯ', 'АКСЕССУАРЫ_ВРАТАРЯ', 'Защита шеи вратаря', 'ВРАТАРСКАЯ_ФОРМА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (27, 'ЗАЩИТА_ГОРЛА_ВРАТАРЯ', 'АКСЕССУАРЫ_ВРАТАРЯ', 'Защита горла вратаря', 'ВРАТАРСКАЯ_ФОРМА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (28, 'ЗАЩИТА_ПАХА_ВРАТАРЯ', 'АКСЕССУАРЫ_ВРАТАРЯ', 'Защита паха вратаря', 'ВРАТАРСКАЯ_ФОРМА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (29, 'ЗАЩИТА_КОЛЕНЕЙ_ВРАТАРЯ', 'АКСЕССУАРЫ_ВРАТАРЯ', 'Защита коленей вратаря', 'ВРАТАРСКАЯ_ФОРМА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (30, 'ПОЯС_ВРАТАРЯ', 'АКСЕССУАРЫ_ВРАТАРЯ', 'Пояс вратаря', 'ВРАТАРСКАЯ_ФОРМА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (36, 'ШНУРКИ', 'АКСЕССУАРЫ_ДЛЯ_КОНЬКОВ', 'Шнурки', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (37, 'ЗАПЧАСТИ', 'АКСЕССУАРЫ_ДЛЯ_ШЛЕМА', 'Запчасти для шлема', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (38, 'АНТИФОГ', 'АКСЕССУАРЫ_ДЛЯ_ШЛЕМА', 'Антифог', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (39, 'ПОДШЛЕМНИКИ', 'АКСЕССУАРЫ_ДЛЯ_ШЛЕМА', 'Подшлемник', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (18, null, 'ТРЕНИРОВОЧНЫЕ_МАЙКИ', 'Хоккейная майка', 'ОДЕЖДА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (19, null, 'НАТЕЛЬНОЕ_БЕЛЬЕ', 'Нательное белье', 'ОДЕЖДА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (40, 'ЛЕНТА', 'АКСЕССУАРЫ_ДЛЯ_КЛЮШЕК', 'Лента', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (41, 'БУТЫЛКИ', 'АКСЕССУАРЫ_ДЛЯ_ИГРОКА', 'Бутылка', 'АКСЕССУАРЫ');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (5, null, 'ШЛЕМ_ИГРОКА', 'Шлем', 'ЗАЩИТА_ИГРОКА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (6, null, 'ЗАЩИТА_ПАХА_ИГРОКА', 'Защита паха', 'ЗАЩИТА_ИГРОКА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (7, null, 'НАЛОКОТНИКИ_ИГРОКА', 'Налокотники', 'ЗАЩИТА_ИГРОКА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (8, null, 'ТРУСЫ_ИГРОКА', 'Трусы', 'ЗАЩИТА_ИГРОКА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (20, null, 'НАГРУДНИК_ВРАТАРЯ', 'Нагрудник вратаря', 'ВРАТАРСКАЯ_ФОРМА');
INSERT INTO public.type (type_id, lower, medium, show_name, upper) VALUES (21, null, 'ТРУСЫ_ВРАТАРЯ', 'Трусы вратаря', 'ВРАТАРСКАЯ_ФОРМА');